version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - apt-get update -y
      - apt-get install -y php8.3-curl php8.3-mbstring php8.3-xml
  pre_build:
    commands:
      - composer install --no-dev
  build:
    commands:
      - php artisan config:cache
      - php artisan route:cache
      - php artisan view:cache
  post_build:
    commands:
      - echo "Build completed on `date`"

artifacts:
  files:
    - '**/*'
  name: $(date +%Y-%m-%d)
  discard-paths: no